os: dos #dos o unix
device: cuda
#-------------DIRECTORIES------------
train: "/scratch1/afilippelli/balanced/train/"
train_masks: "/scratch1/afilippelli/balanced/trainannot/"
val: "/scratch1/afilippelli/balanced/val/"
val_masks: "/scratch1/afilippelli/balanced/valannot/"
test: "/scratch1/afilippelli/balanced/test/"
test_masks: "/scratch1/afilippelli/balanced/testannot/"
results_dir: /scratch1/afilippelli/results_seg_r50
#----NET AND CONTEXT----------
model_name: "SegFormer"
encoder: "resnet50"
encoder_weights: "imagenet"
dropout: 0.43
patience: 50
learning_rate: 0.0001
save_criterion: "mean_IoU"
#-------DATA LOADING----------
classes: ["background", "tumor", "necrosis", "tissue", "cirrhotic_tissue", "exogenous_material"]
epochs: 300
patch_size: 512
batch_size: 4
augmentation: True
# ------LOSS AND OPTIMIZATION----------
loss: dice
opt: ADAM1
